### ISSUE TITLE
GitHub Enterprise support

### ISSUE THREAD

**Issue by fly** [akerl/githubstats#25]
handle environment variables, or by parsing .gitconfig.

```
GITHUB_HOST=enterprise.fizzbuzz.com
GITHUB_URL=https://enterprise.fizzbuzz.com/
```
or
```
[github]
	host = enterprise.fizzbuzz.com
```

**Comment by gcochard** [comment]
As of GitHub Enterprise 2.1 the URL to fetch the stats is the same. Some GH:E instances are behind a firewall, and thus do not need auth, so handling this via environment vars should be possible.

**Comment by akerl** [comment]
Granted. I'll take a look at this tonight if I get a moment

**Comment by akerl** [comment]
@gcochard this should be sorted in 1.0.1, but I don't have a GHE environment to test it with; any chance you can confirm?

**Comment by gcochard** [comment]
@akerl My environment has login required for any access, so it'd have to also include a login feature for me to verify.
